name: Manual Service Build and push to Artifactory

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Service name"
        required: true
        type: choice
        options:
          - profile-service
          - recommendation-service
          - match-service
          - reaction-service
          - shared-module
      tag:
        description: "Tag for the Docker image"
        required: false
      push:
        description: "Should push to Artifactory"
        type: boolean
        default: false

jobs:
  build-and-push:
    runs-on: [self-hosted, arm64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Nexus Docker registry
        if: ${{ github.event.inputs.push == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.NEXUS_URL_LOCAL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: be-components/${{ github.event.inputs.service }}/Dockerfile
          push: ${{ github.event.inputs.push == 'true' }}
          tags: |
            ${{ vars.NEXUS_URL_LOCAL }}/${{ github.event.inputs.service }}:${{ github.event.inputs.tag || github.sha }}
          load: ${{ github.event.inputs.push == 'false' }}

      - name: Update GitOps repo
        if: ${{ github.event.inputs.push == 'true' }}
        uses: ./.github/actions/update-gitops-tag
        with:
          service-name: ${{ github.event.inputs.service }}
          deployment-file-path: argocd/base/tinder-app/${{ github.event.inputs.service }}/deployment.yaml
          image-tag: ${{ github.event.inputs.tag || github.sha }}
          gitops-repo: ${{ vars.TINDER_CLOUD_GITOPS_REPO }}
          gitops-token: ${{ secrets.TINDER_CLOUD_GITOPS_PAT }}
